import type { Metadata } from "next";
import { Inter, Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { PaletteProvider } from "@/styles/PaletteProvider";
import { AuthProvider } from "@/core/services/AuthProvider";
import { LanguageProvider } from "@/core/services/LanguageProvider";
import Navbar from "@/components/Navbar";
import { PaletteSyncWrapper } from "@/components/PaletteSyncWrapper";
import { BannerColorSyncWrapper } from "@/components/BannerColorSyncWrapper";

const inter = Inter({
 variable: "--font-inter",
 subsets: ["latin"],
 display: "swap",
});
const manrope = Manrope({
 variable: "--font-manrope",
 subsets: ["latin"],
 display: "swap",
});
const jetbrains = JetBrains_Mono({
 variable: "--font-jetbrains",
 subsets: ["latin"],
 display: "swap",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html
   lang="en"
   className={`${inter.variable} ${manrope.variable} ${jetbrains.variable}`}
  >
   <body>
    <AuthProvider>
     <PaletteProvider>
      <LanguageProvider>
       <PaletteSyncWrapper />
       <BannerColorSyncWrapper />
       <Navbar />
       {children}
      </LanguageProvider>
     </PaletteProvider>
    </AuthProvider>
   </body>
  </html>
 );
}
