import type { Metadata } from "next";
import { Inter, Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { PaletteProvider, PaletteName } from "@/styles/PaletteProvider";
import { bgBannerColor } from "@/styles/sharedStyleConstants";
import { AuthProvider } from "@/core/services/AuthProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({
 variable: "--font-inter",
 subsets: ["latin"],
 display: "swap",
});
const manrope = Manrope({
 variable: "--font-manrope",
 subsets: ["latin"],
 display: "swap",
});
const jetbrains = JetBrains_Mono({
 variable: "--font-jetbrains",
 subsets: ["latin"],
 display: "swap",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 // Get palette from query string (on client only)
 let initialPalette: PaletteName = "darkGreen";
 if (typeof window !== "undefined") {
  const params = new URLSearchParams(window.location.search);
  const paletteParam = params.get("palette");
  if (paletteParam && Object.keys(bgBannerColor).includes(paletteParam)) {
   initialPalette = paletteParam as PaletteName;
  }
 }
 return (
  <html lang="en">
   <body
    className={`${inter.variable} ${manrope.variable} ${jetbrains.variable} font-sans antialiased`}
    suppressHydrationWarning
   >
    <AuthProvider>
     <PaletteProvider initialPalette={initialPalette}>
      <Navbar />
      {children}
     </PaletteProvider>
    </AuthProvider>
   </body>
  </html>
 );
}
