import type { Metadata } from "next";
import { Inter, Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
 variable: "--font-inter",
 subsets: ["latin"],
 display: "swap",
});
const manrope = Manrope({
 variable: "--font-manrope",
 subsets: ["latin"],
 display: "swap",
});
const jetbrains = JetBrains_Mono({
 variable: "--font-jetbrains",
 subsets: ["latin"],
 display: "swap",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body
    className={`${inter.variable} ${manrope.variable} ${jetbrains.variable} font-sans antialiased`}
    suppressHydrationWarning
   >
    {children}
   </body>
  </html>
 );
}
